### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by santiagobasulto** [markcapece/dementia#1]
Hey Mark! I'll leave a technical review. @sbaezrmotr will take care of helping you make it as "professional and presentable" as possible.

1. The repo is confusing without a Readme. Add a readme with a quick explanation of what the project is about and where the analysis starts (in the `MRI_and_Alzheimers.ipynb` notebook for now). If you can move the data files to a `data/` directory, that'll help too. Think about the first impression of someone looking at your readme.

2. Great introduction and details in Notebook! It looks very well organized and explained. Amazing work there.

3. Try moving utility functions to their own Python module. That way you'll reduce noise in the notebook. The function `transform_data` should receive the filenames to read as parameters, so it's reusable later. A function without parameters is usually pointless.

4. Interesting idea putting the code inside a class. Makes it readable when using it.

5. You seem to have a lot of code commented. I think you're in a point when it makes sense to break your analysis in multiple notebooks. And just guide the reader through them. The ones with support will be optional for the reader.

Great work so far! I'll double check the ML part with more detail, and I'll probably need to ask you a couple of questions.

**Comment by markcapece** [comment]
Thanks Santiago!
1. I added a readme.
2. Thanks!
3. The notebook was entirely reorganized. All of the classes and functions were moved to the dementia module. `transform_data()` now takes path arguments.
4. Thanks!
5. All of the commented code was removed. The "dirty," unsupported notebook was saved in a separate folder.
